//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreAppFront.Domain.PizzaDataServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class AddressDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class PhoneDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneId {
            get {
                return this.PhoneIdField;
            }
            set {
                if ((this.PhoneIdField.Equals(value) != true)) {
                    this.PhoneIdField = value;
                    this.RaisePropertyChanged("PhoneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class StoreDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesTax {
            get {
                return this.SalesTaxField;
            }
            set {
                if ((this.SalesTaxField.Equals(value) != true)) {
                    this.SalesTaxField = value;
                    this.RaisePropertyChanged("SalesTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((this.StoreIdField.Equals(value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class PersonDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class OrderDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((this.TaxField.Equals(value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IngredientDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class IngredientDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IngredientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IngredientId {
            get {
                return this.IngredientIdField;
            }
            set {
                if ((this.IngredientIdField.Equals(value) != true)) {
                    this.IngredientIdField = value;
                    this.RaisePropertyChanged("IngredientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class PizzaDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] IngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] Ingredients {
            get {
                return this.IngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientsField, value) != true)) {
                    this.IngredientsField = value;
                    this.RaisePropertyChanged("Ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaId {
            get {
                return this.PizzaIdField;
            }
            set {
                if ((this.PizzaIdField.Equals(value) != true)) {
                    this.PizzaIdField = value;
                    this.RaisePropertyChanged("PizzaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SizeDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreAppBack.DataClient.Models")]
    [System.SerializableAttribute()]
    public partial class SizeDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dimension {
            get {
                return this.DimensionField;
            }
            set {
                if ((this.DimensionField.Equals(value) != true)) {
                    this.DimensionField = value;
                    this.RaisePropertyChanged("Dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeId {
            get {
                return this.SizeIdField;
            }
            set {
                if ((this.SizeIdField.Equals(value) != true)) {
                    this.SizeIdField = value;
                    this.RaisePropertyChanged("SizeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaDataServiceReference.IPizzaDataService")]
    public interface IPizzaDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetAddress", ReplyAction="http://tempuri.org/IPizzaDataService/GetAddressResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO GetAddress(int addressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetAddress", ReplyAction="http://tempuri.org/IPizzaDataService/GetAddressResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO> GetAddressAsync(int addressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPhone", ReplyAction="http://tempuri.org/IPizzaDataService/GetPhoneResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO GetPhone(int phoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPhone", ReplyAction="http://tempuri.org/IPizzaDataService/GetPhoneResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO> GetPhoneAsync(int phoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetStore", ReplyAction="http://tempuri.org/IPizzaDataService/GetStoreResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO GetStore(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetStore", ReplyAction="http://tempuri.org/IPizzaDataService/GetStoreResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO> GetStoreAsync(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPerson", ReplyAction="http://tempuri.org/IPizzaDataService/GetPersonResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO GetPerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPerson", ReplyAction="http://tempuri.org/IPizzaDataService/GetPersonResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO> GetPersonAsync(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStores", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoresResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[] ListStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStores", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoresResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[]> ListStoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStoreOrders", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoreOrdersResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[] ListStoreOrders(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStoreOrders", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoreOrdersResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[]> ListStoreOrdersAsync(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPeople", ReplyAction="http://tempuri.org/IPizzaDataService/ListPeopleResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[] ListPeople();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPeople", ReplyAction="http://tempuri.org/IPizzaDataService/ListPeopleResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[]> ListPeopleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCrusts", ReplyAction="http://tempuri.org/IPizzaDataService/ListCrustsResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCrusts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCrusts", ReplyAction="http://tempuri.org/IPizzaDataService/ListCrustsResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCrustsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSauces", ReplyAction="http://tempuri.org/IPizzaDataService/ListSaucesResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListSauces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSauces", ReplyAction="http://tempuri.org/IPizzaDataService/ListSaucesResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListSaucesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCheeses", ReplyAction="http://tempuri.org/IPizzaDataService/ListCheesesResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCheeses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCheeses", ReplyAction="http://tempuri.org/IPizzaDataService/ListCheesesResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCheesesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListToppings", ReplyAction="http://tempuri.org/IPizzaDataService/ListToppingsResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListToppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListToppings", ReplyAction="http://tempuri.org/IPizzaDataService/ListToppingsResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListToppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetIngredient", ReplyAction="http://tempuri.org/IPizzaDataService/GetIngredientResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO GetIngredient(int ingredientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetIngredient", ReplyAction="http://tempuri.org/IPizzaDataService/GetIngredientResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO> GetIngredientAsync(int ingredientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/CreateOrder", ReplyAction="http://tempuri.org/IPizzaDataService/CreateOrderResponse")]
        bool CreateOrder(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/CreateOrder", ReplyAction="http://tempuri.org/IPizzaDataService/CreateOrderResponse")]
        System.Threading.Tasks.Task<bool> CreateOrderAsync(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPizzasInOrder", ReplyAction="http://tempuri.org/IPizzaDataService/ListPizzasInOrderResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] ListPizzasInOrder(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPizzasInOrder", ReplyAction="http://tempuri.org/IPizzaDataService/ListPizzasInOrderResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[]> ListPizzasInOrderAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSizes", ReplyAction="http://tempuri.org/IPizzaDataService/ListSizesResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[] ListSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSizes", ReplyAction="http://tempuri.org/IPizzaDataService/ListSizesResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[]> ListSizesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetSize", ReplyAction="http://tempuri.org/IPizzaDataService/GetSizeResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO GetSize(int sizeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetSize", ReplyAction="http://tempuri.org/IPizzaDataService/GetSizeResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO> GetSizeAsync(int sizeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaDataServiceChannel : PizzaStoreAppFront.Domain.PizzaDataServiceReference.IPizzaDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaDataServiceClient : System.ServiceModel.ClientBase<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IPizzaDataService>, PizzaStoreAppFront.Domain.PizzaDataServiceReference.IPizzaDataService {
        
        public PizzaDataServiceClient() {
        }
        
        public PizzaDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO GetAddress(int addressId) {
            return base.Channel.GetAddress(addressId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO> GetAddressAsync(int addressId) {
            return base.Channel.GetAddressAsync(addressId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO GetPhone(int phoneId) {
            return base.Channel.GetPhone(phoneId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO> GetPhoneAsync(int phoneId) {
            return base.Channel.GetPhoneAsync(phoneId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO GetStore(int storeId) {
            return base.Channel.GetStore(storeId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO> GetStoreAsync(int storeId) {
            return base.Channel.GetStoreAsync(storeId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO GetPerson(int personId) {
            return base.Channel.GetPerson(personId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO> GetPersonAsync(int personId) {
            return base.Channel.GetPersonAsync(personId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[] ListStores() {
            return base.Channel.ListStores();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[]> ListStoresAsync() {
            return base.Channel.ListStoresAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[] ListStoreOrders(int storeId) {
            return base.Channel.ListStoreOrders(storeId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[]> ListStoreOrdersAsync(int storeId) {
            return base.Channel.ListStoreOrdersAsync(storeId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[] ListPeople() {
            return base.Channel.ListPeople();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[]> ListPeopleAsync() {
            return base.Channel.ListPeopleAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCrusts() {
            return base.Channel.ListCrusts();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCrustsAsync() {
            return base.Channel.ListCrustsAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListSauces() {
            return base.Channel.ListSauces();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListSaucesAsync() {
            return base.Channel.ListSaucesAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCheeses() {
            return base.Channel.ListCheeses();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCheesesAsync() {
            return base.Channel.ListCheesesAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListToppings() {
            return base.Channel.ListToppings();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListToppingsAsync() {
            return base.Channel.ListToppingsAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO GetIngredient(int ingredientId) {
            return base.Channel.GetIngredient(ingredientId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO> GetIngredientAsync(int ingredientId) {
            return base.Channel.GetIngredientAsync(ingredientId);
        }
        
        public bool CreateOrder(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total) {
            return base.Channel.CreateOrder(storeId, customerId, pizzasDAOs, subTotal, taxTotal, total);
        }
        
        public System.Threading.Tasks.Task<bool> CreateOrderAsync(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total) {
            return base.Channel.CreateOrderAsync(storeId, customerId, pizzasDAOs, subTotal, taxTotal, total);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] ListPizzasInOrder(int orderId) {
            return base.Channel.ListPizzasInOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[]> ListPizzasInOrderAsync(int orderId) {
            return base.Channel.ListPizzasInOrderAsync(orderId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[] ListSizes() {
            return base.Channel.ListSizes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[]> ListSizesAsync() {
            return base.Channel.ListSizesAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO GetSize(int sizeId) {
            return base.Channel.GetSize(sizeId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO> GetSizeAsync(int sizeId) {
            return base.Channel.GetSizeAsync(sizeId);
        }
    }
}
