//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreAppFront.Api.PizzaDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaDataServiceReference.IPizzaDataService")]
    public interface IPizzaDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetAddress", ReplyAction="http://tempuri.org/IPizzaDataService/GetAddressResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO GetAddress(int addressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetAddress", ReplyAction="http://tempuri.org/IPizzaDataService/GetAddressResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO> GetAddressAsync(int addressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPhone", ReplyAction="http://tempuri.org/IPizzaDataService/GetPhoneResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO GetPhone(int phoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPhone", ReplyAction="http://tempuri.org/IPizzaDataService/GetPhoneResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO> GetPhoneAsync(int phoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetStore", ReplyAction="http://tempuri.org/IPizzaDataService/GetStoreResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO GetStore(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetStore", ReplyAction="http://tempuri.org/IPizzaDataService/GetStoreResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO> GetStoreAsync(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPerson", ReplyAction="http://tempuri.org/IPizzaDataService/GetPersonResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO GetPerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetPerson", ReplyAction="http://tempuri.org/IPizzaDataService/GetPersonResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO> GetPersonAsync(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStores", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoresResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[] ListStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStores", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoresResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[]> ListStoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStoreOrders", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoreOrdersResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[] ListStoreOrders(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListStoreOrders", ReplyAction="http://tempuri.org/IPizzaDataService/ListStoreOrdersResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[]> ListStoreOrdersAsync(int storeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPeople", ReplyAction="http://tempuri.org/IPizzaDataService/ListPeopleResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[] ListPeople();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPeople", ReplyAction="http://tempuri.org/IPizzaDataService/ListPeopleResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[]> ListPeopleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCrusts", ReplyAction="http://tempuri.org/IPizzaDataService/ListCrustsResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCrusts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCrusts", ReplyAction="http://tempuri.org/IPizzaDataService/ListCrustsResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCrustsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSauces", ReplyAction="http://tempuri.org/IPizzaDataService/ListSaucesResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListSauces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSauces", ReplyAction="http://tempuri.org/IPizzaDataService/ListSaucesResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListSaucesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCheeses", ReplyAction="http://tempuri.org/IPizzaDataService/ListCheesesResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCheeses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListCheeses", ReplyAction="http://tempuri.org/IPizzaDataService/ListCheesesResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCheesesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListToppings", ReplyAction="http://tempuri.org/IPizzaDataService/ListToppingsResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListToppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListToppings", ReplyAction="http://tempuri.org/IPizzaDataService/ListToppingsResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListToppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetIngredient", ReplyAction="http://tempuri.org/IPizzaDataService/GetIngredientResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO GetIngredient(int ingredientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetIngredient", ReplyAction="http://tempuri.org/IPizzaDataService/GetIngredientResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO> GetIngredientAsync(int ingredientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/CreateOrder", ReplyAction="http://tempuri.org/IPizzaDataService/CreateOrderResponse")]
        bool CreateOrder(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/CreateOrder", ReplyAction="http://tempuri.org/IPizzaDataService/CreateOrderResponse")]
        System.Threading.Tasks.Task<bool> CreateOrderAsync(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPizzasInOrder", ReplyAction="http://tempuri.org/IPizzaDataService/ListPizzasInOrderResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] ListPizzasInOrder(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListPizzasInOrder", ReplyAction="http://tempuri.org/IPizzaDataService/ListPizzasInOrderResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[]> ListPizzasInOrderAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSizes", ReplyAction="http://tempuri.org/IPizzaDataService/ListSizesResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[] ListSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/ListSizes", ReplyAction="http://tempuri.org/IPizzaDataService/ListSizesResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[]> ListSizesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetSize", ReplyAction="http://tempuri.org/IPizzaDataService/GetSizeResponse")]
        PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO GetSize(int sizeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaDataService/GetSize", ReplyAction="http://tempuri.org/IPizzaDataService/GetSizeResponse")]
        System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO> GetSizeAsync(int sizeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaDataServiceChannel : PizzaStoreAppFront.Api.PizzaDataServiceReference.IPizzaDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaDataServiceClient : System.ServiceModel.ClientBase<PizzaStoreAppFront.Api.PizzaDataServiceReference.IPizzaDataService>, PizzaStoreAppFront.Api.PizzaDataServiceReference.IPizzaDataService {
        
        public PizzaDataServiceClient() {
        }
        
        public PizzaDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO GetAddress(int addressId) {
            return base.Channel.GetAddress(addressId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.AddressDAO> GetAddressAsync(int addressId) {
            return base.Channel.GetAddressAsync(addressId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO GetPhone(int phoneId) {
            return base.Channel.GetPhone(phoneId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PhoneDAO> GetPhoneAsync(int phoneId) {
            return base.Channel.GetPhoneAsync(phoneId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO GetStore(int storeId) {
            return base.Channel.GetStore(storeId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO> GetStoreAsync(int storeId) {
            return base.Channel.GetStoreAsync(storeId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO GetPerson(int personId) {
            return base.Channel.GetPerson(personId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO> GetPersonAsync(int personId) {
            return base.Channel.GetPersonAsync(personId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[] ListStores() {
            return base.Channel.ListStores();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.StoreDAO[]> ListStoresAsync() {
            return base.Channel.ListStoresAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[] ListStoreOrders(int storeId) {
            return base.Channel.ListStoreOrders(storeId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.OrderDAO[]> ListStoreOrdersAsync(int storeId) {
            return base.Channel.ListStoreOrdersAsync(storeId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[] ListPeople() {
            return base.Channel.ListPeople();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PersonDAO[]> ListPeopleAsync() {
            return base.Channel.ListPeopleAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCrusts() {
            return base.Channel.ListCrusts();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCrustsAsync() {
            return base.Channel.ListCrustsAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListSauces() {
            return base.Channel.ListSauces();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListSaucesAsync() {
            return base.Channel.ListSaucesAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListCheeses() {
            return base.Channel.ListCheeses();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListCheesesAsync() {
            return base.Channel.ListCheesesAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[] ListToppings() {
            return base.Channel.ListToppings();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO[]> ListToppingsAsync() {
            return base.Channel.ListToppingsAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO GetIngredient(int ingredientId) {
            return base.Channel.GetIngredient(ingredientId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.IngredientDAO> GetIngredientAsync(int ingredientId) {
            return base.Channel.GetIngredientAsync(ingredientId);
        }
        
        public bool CreateOrder(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total) {
            return base.Channel.CreateOrder(storeId, customerId, pizzasDAOs, subTotal, taxTotal, total);
        }
        
        public System.Threading.Tasks.Task<bool> CreateOrderAsync(int storeId, int customerId, PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] pizzasDAOs, decimal subTotal, decimal taxTotal, decimal total) {
            return base.Channel.CreateOrderAsync(storeId, customerId, pizzasDAOs, subTotal, taxTotal, total);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[] ListPizzasInOrder(int orderId) {
            return base.Channel.ListPizzasInOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.PizzaDAO[]> ListPizzasInOrderAsync(int orderId) {
            return base.Channel.ListPizzasInOrderAsync(orderId);
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[] ListSizes() {
            return base.Channel.ListSizes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO[]> ListSizesAsync() {
            return base.Channel.ListSizesAsync();
        }
        
        public PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO GetSize(int sizeId) {
            return base.Channel.GetSize(sizeId);
        }
        
        public System.Threading.Tasks.Task<PizzaStoreAppFront.Domain.PizzaDataServiceReference.SizeDAO> GetSizeAsync(int sizeId) {
            return base.Channel.GetSizeAsync(sizeId);
        }
    }
}
